#test read ymlfile
fruit:
    name: apple
    amount: 5

#自定义的属性和值
myProps:
  simpleProp: simplePropValue
  arrayProps: 1,2,3,4,5
  listProp1:
    - name: abc
      value: abcValue
    - name: efg
      value: efgValue
  listProp2:
    - config2Value1
    - config2Vavlue2
  mapProps:
    key1: value1
    key2: value2




#spring profiles
spring:
    #http encoding
    http:
        encoding.charset: UTF-8
        encoding.enable: true
        encoding.force: true

#servers setting
server:
    port: 8080
    address: localhost
    context-path: /springboot-jpa

#datasource
datasource:
     #mysql
     driver: com.mysql.jdbc.Driver
     url: mysql://localhost:3306/kevin?useUnicode=true&characterEncoding=utf-8
     username: root
     password: root
     #oracle
     #driver: oracle.jdbc.driver.OracleDriver
     #url: jdbc:oracle:thin:@localhost:1521:orcl
     #user: kevin
     #password: kevin
     # 使用druid数据源
     type: com.alibaba.druid.pool.DruidDataSource
     filters: stat
     maxActive: 20
     initialSize: 1
     maxWait: 60000
     minIdle: 1
     timeBetweenEvictionRunsMillis: 60000
     minEvictableIdleTimeMillis: 300000
     validationQuery: select 'x'
     testWhileIdle: true
     testOnBorrow: false
     testOnReturn: false
     poolPreparedStatements: true
     maxOpenPreparedStatements: 20

#mybatis
mybatis:
     typeAliasesPackage: com.kevin.entity
     mapperLocations: classpath:/resouces/mybatis/*.xml
#     configLocation: classpath:/resouces/mybatis-config.xml

# LOGGING
logging:
    level: com.ibatis:DEBUG







